# Generated by Django 4.2 on 2024-06-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='images/'),
        ),
    ]
