# Generated by Django 4.2 on 2024-06-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursemodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='file',
        ),
    ]
