# Generated by Django 4.2 on 2024-06-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_coursemodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='files/'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
