# Generated by Django 4.2 on 2024-05-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.CharField(default='empty', max_length=30),
        ),
    ]
