# Generated by Django 4.2 on 2024-05-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='logo_image',
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
