# Generated by Django 4.2 on 2024-05-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotype',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='videotype',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
